enationallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.contrib.auth import views as auth_views

admin.site.index_title = "Trang quản trị"

urlpatterns = [
    path('home/', include('home.urls')),
    path('location/', include('location.urls')),
    path('login/', include('login.urls')),
    path('category/', include('category.urls')),
    path('myaccount/', include('myaccount.urls')),
    path('news/', include('news.urls')),
    path('services/', include('services.urls')),
    path('support/', include('support.urls')),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/email_verification.html',
                                                                 email_template_name='registration/password_reset_email.html'),
         name='password_reset'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/reset_password.html'),
         name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_success.html'),
         name='password_reset_complete'),
    # path('forest', include('django_forest.urls')),
]

handler404 = "enationallibrary.views.page_not_found_view"
handler500 = "enationallibrary.views.server_error_view"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='homepage'),
]

templates/404_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Không tìm thấy trang | Thư viện số quốc gia</title>
    <link rel="icon"
    href="https://res.cloudinary.com/enationallibrary/image/upload/v1638580740/media/favicon-32x32_unmryt.png"
    type="image/png" sizes="32x32">
    <style>
        @import url(https://fonts.googleapis.com/css?family=opensans:500);

        body {
            background: #33cc99;
            color: #fff;
            font-family: 'Open Sans', sans-serif;
            max-height: 700px;
            overflow: hidden;
        }

        .c {
            text-align: center;
            display: block;
            position: relative;
            width: 80%;
            margin: 100px auto;
        }

        ._404 {
            font-size: 180px;
            position: relative;
            display: inline-block;
            z-index: 2;
            height: 200px;
            letter-spacing: 15px;
            user-select: none;
        }

        ._1 {
            text-align: center;
            display: block;
            position: relative;
            letter-spacing: 12px;
            font-size: 4em;
            line-height: 80%;
            user-select: none;
        }

        ._2 {
            margin-top: 10px;
            margin-bottom: 10px;
            text-align: center;
            display: block;
            position: relative;
            font-size: 40px;
            user-select: none;
        }

        .text {
            font-size: 70px;
            text-align: center;
            position: relative;
            display: inline-block;
            margin: 19px 0px 0px 0px;
            z-index: 3;
            width: 100%;
            line-height: 1.2em;
            display: inline-block;
        }


        .btn {
            background-color: rgb(255, 255, 255);
            position: relative;
            display: inline-block;
            width: 358px;
            padding: 5px;
            z-index: 5;
            font-size: 25px;
            margin: 0 auto;
            color: #33cc99;
            text-decoration: none;
            margin-right: 10px
        }

        .right {
            float: right;
            width: 60%;
        }

        hr {
            padding: 0;
            border: none;
            border-top: 5px solid #fff;
            color: #fff;
            text-align: center;
            margin: 0px auto;
            width: 420px;
            height: 10px;
            z-index: -10;
        }

        hr:after {
            content: "\2022";
            display: inline-block;
            position: relative;
            top: -0.75em;
            font-size: 2em;
            padding: 0 0.2em;
            background: #33cc99;
        }

        .cloud {
            width: 350px;
            height: 120px;

            background: #FFF;
            background: linear-gradient(top, #FFF 100%);
            background: -webkit-linear-gradient(top, #FFF 100%);
            background: -moz-linear-gradient(top, #FFF 100%);
            background: -ms-linear-gradient(top, #FFF 100%);
            background: -o-linear-gradient(top, #FFF 100%);

            border-radius: 100px;
            -webkit-border-radius: 100px;
            -moz-border-radius: 100px;

            position: absolute;
            margin: 120px auto 20px;
            z-index: -1;
            transition: ease 1s;
        }

        .cloud:after,
        .cloud:before {
            content: '';
            position: absolute;
            background: #FFF;
            z-index: -1
        }

        .cloud:after {
            width: 100px;
            height: 100px;
            top: -50px;
            left: 50px;

            border-radius: 100px;
            -webkit-border-radius: 100px;
            -moz-border-radius: 100px;
        }

        .cloud:before {
            width: 180px;
            height: 180px;
            top: -90px;
            right: 50px;

            border-radius: 200px;
            -webkit-border-radius: 200px;
            -moz-border-radius: 200px;
        }

        .x1 {
            top: -50px;
            left: 100px;
            -webkit-transform: scale(0.3);
            -moz-transform: scale(0.3);
            transform: scale(0.3);
            opacity: 0.9;
            -webkit-animation: moveclouds 15s linear infinite;
            -moz-animation: moveclouds 15s linear infinite;
            -o-animation: moveclouds 15s linear infinite;
        }

        .x1_5 {
            top: -80px;
            left: 250px;
            -webkit-transform: scale(0.3);
            -moz-transform: scale(0.3);
            transform: scale(0.3);
            -webkit-animation: moveclouds 17s linear infinite;
            -moz-animation: moveclouds 17s linear infinite;
            -o-animation: moveclouds 17s linear infinite;
        }

        .x2 {
            left: 250px;
            top: 30px;
            -webkit-transform: scale(0.6);
            -moz-transform: scale(0.6);
            transform: scale(0.6);
            opacity: 0.6;
            -webkit-animation: moveclouds 25s linear infinite;
            -moz-animation: moveclouds 25s linear infinite;
            -o-animation: moveclouds 25s linear infinite;
        }

        .x3 {
            left: 250px;
            bottom: -70px;

            -webkit-transform: scale(0.6);
            -moz-transform: scale(0.6);
            transform: scale(0.6);
            opacity: 0.8;

            -webkit-animation: moveclouds 25s linear infinite;
            -moz-animation: moveclouds 25s linear infinite;
            -o-animation: moveclouds 25s linear infinite;
        }

        .x4 {
            left: 470px;
            botttom: 20px;

            -webkit-transform: scale(0.75);
            -moz-transform: scale(0.75);
            transform: scale(0.75);
            opacity: 0.75;

            -webkit-animation: moveclouds 18s linear infinite;
            -moz-animation: moveclouds 18s linear infinite;
            -o-animation: moveclouds 18s linear infinite;
        }

        .x5 {
            left: 200px;
            top: 300px;

            -webkit-transform: scale(0.5);
            -moz-transform: scale(0.5);
            transform: scale(0.5);
            opacity: 0.8;

            -webkit-animation: moveclouds 20s linear infinite;
            -moz-animation: moveclouds 20s linear infinite;
            -o-animation: moveclouds 20s linear infinite;
        }

        @-webkit-keyframes moveclouds {
            0% {
                margin-left: 1000px;
            }

            100% {
                margin-left: -1000px;
            }
        }

        @-moz-keyframes moveclouds {
            0% {
                margin-left: 1000px;
            }

            100% {
                margin-left: -1000px;
            }
        }

        @-o-keyframes moveclouds {
            0% {
                margin-left: 1000px;
            }

            100% {
                margin-left: -1000px;
            }
        }
    </style>
</head>

<body>
    <div id="clouds">
        <div class="cloud x1"></div>
        <div class="cloud x1_5"></div>
        <div class="cloud x2"></div>
        <div class="cloud x3"></div>
        <div class="cloud x4"></div>
        <div class="cloud x5"></div>
    </div>
    <div class='c'>
        <div class='_404'>404</div>
        <hr>
        <div class='_1'>Không tìm thấy</div>
        <div class='_2'>trang yêu cầu</div>
        <a class='btn' href='{% url 'home:homepage' %}'>Quay trở lại trang chủ</a>
    </div>
</body>

</html>

templates/500_page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lỗi máy chủ | Thư viện số quốc gia</title>
    <link rel="icon"
    href="https://res.cloudinary.com/enationallibrary/image/upload/v1638580740/media/favicon-32x32_unmryt.png"
    type="image/png" sizes="32x32">
    <style>
        @import url(https://fonts.googleapis.com/css?family=opensans:500);

        body {
            background: #33cc99;
            color: #fff;
            font-family: 'Open Sans', sans-serif;
            max-height: 700px;
            overflow: hidden;
        }

        .c {
            text-align: center;
            display: block;
            position: relative;
            width: 80%;
            margin: 100px auto;
        }

        ._404 {
            font-size: 180px;
            position: relative;
            display: inline-block;
            z-index: 2;
            height: 200px;
            letter-spacing: 15px;
            user-select: none;
        }

        ._1 {
            text-align: center;
            display: block;
            position: relative;
            letter-spacing: 12px;
            font-size: 4em;
            line-height: 80%;
            user-select: none;
        }

        ._2 {
            margin-top: 10px;
            margin-bottom: 10px;
            text-align: center;
            display: block;
            position: relative;
            font-size: 40px;
            user-select: none;
        }

        .text {
            font-size: 70px;
            text-align: center;
            position: relative;
            display: inline-block;
            margin: 19px 0px 0px 0px;
            z-index: 3;
            width: 100%;
            line-height: 1.2em;
            display: inline-block;
        }


        .btn {
            background-color: rgb(255, 255, 255);
            position: relative;
            display: inline-block;
            width: 358px;
            padding: 5px;
            z-index: 5;
            font-size: 25px;
            margin: 0 auto;
            color: #33cc99;
            text-decoration: none;
            margin-right: 10px
        }

        .right {
            float: right;
            width: 60%;
        }

        hr {
            padding: 0;
            border: none;
            border-top: 5px solid #fff;
            color: #fff;
            text-align: center;
            margin: 0px auto;
            width: 420px;
            height: 10px;
            z-index: -10;
        }

        hr:after {
            content: "\2022";
            display: inline-block;
            position: relative;
            top: -0.75em;
            font-size: 2em;
            padding: 0 0.2em;
            background: #33cc99;
        }

        .cloud {
            width: 350px;
            height: 120px;

            background: #FFF;
            background: linear-gradient(top, #FFF 100%);
            background: -webkit-linear-gradient(top, #FFF 100%);
            background: -moz-linear-gradient(top, #FFF 100%);
            background: -ms-linear-gradient(top, #FFF 100%);
            background: -o-linear-gradient(top, #FFF 100%);

            border-radius: 100px;
            -webkit-border-radius: 100px;
            -moz-border-radius: 100px;

            position: absolute;
            margin: 120px auto 20px;
            z-index: -1;
            transition: ease 1s;
        }

        .cloud:after,
        .cloud:before {
            content: '';
            position: absolute;
            background: #FFF;
            z-index: -1
        }

        .cloud:after {
            width: 100px;
            height: 100px;
            top: -50px;
            left: 50px;

            border-radius: 100px;
            -webkit-border-radius: 100px;
            -moz-border-radius: 100px;
        }

        .cloud:before {
            width: 180px;
            height: 180px;
            top: -90px;
            right: 50px;

            border-radius: 200px;
            -webkit-border-radius: 200px;
            -moz-border-radius: 200px;
        }

        .x1 {
            top: -50px;
            left: 100px;
            -webkit-transform: scale(0.3);
            -moz-transform: scale(0.3);
            transform: scale(0.3);
            opacity: 0.9;
            -webkit-animation: moveclouds 15s linear infinite;
            -moz-animation: moveclouds 15s linear infinite;
            -o-animation: moveclouds 15s linear infinite;
        }

        .x1_5 {
            top: -80px;
            left: 250px;
            -webkit-transform: scale(0.3);
            -moz-transform: scale(0.3);
            transform: scale(0.3);
            -webkit-animation: moveclouds 17s linear infinite;
            -moz-animation: moveclouds 17s linear infinite;
            -o-animation: moveclouds 17s linear infinite;
        }

        .x2 {
            left: 250px;
            top: 30px;
            -webkit-transform: scale(0.6);
            -moz-transform: scale(0.6);
            transform: scale(0.6);
            opacity: 0.6;
            -webkit-animation: moveclouds 25s linear infinite;
            -moz-animation: moveclouds 25s linear infinite;
            -o-animation: moveclouds 25s linear infinite;
        }

        .x3 {
            left: 250px;
            bottom: -70px;

            -webkit-transform: scale(0.6);
            -moz-transform: scale(0.6);
            transform: scale(0.6);
            opacity: 0.8;

            -webkit-animation: moveclouds 25s linear infinite;
            -moz-animation: moveclouds 25s linear infinite;
            -o-animation: moveclouds 25s linear infinite;
        }

        .x4 {
            left: 470px;
            botttom: 20px;

            -webkit-transform: scale(0.75);
            -moz-transform: scale(0.75);
            transform: scale(0.75);
            opacity: 0.75;

            -webkit-animation: moveclouds 18s linear infinite;
            -moz-animation: moveclouds 18s linear infinite;
            -o-animation: moveclouds 18s linear infinite;
        }

        .x5 {
            left: 200px;
            top: 300px;

            -webkit-transform: scale(0.5);
            -moz-transform: scale(0.5);
            transform: scale(0.5);
            opacity: 0.8;

            -webkit-animation: moveclouds 20s linear infinite;
            -moz-animation: moveclouds 20s linear infinite;
            -o-animation: moveclouds 20s linear infinite;
        }

        @-webkit-keyframes moveclouds {
            0% {
                margin-left: 1000px;
            }

            100% {
                margin-left: -1000px;
            }
        }

        @-moz-keyframes moveclouds {
            0% {
                margin-left: 1000px;
            }

            100% {
                margin-left: -1000px;
            }
        }

        @-o-keyframes moveclouds {
            0% {
                margin-left: 1000px;
            }

            100% {
                margin-left: -1000px;
            }
        }
    </style>
</head>

<body>
    <div id="clouds">
        <div class="cloud x1"></div>
        <div class="cloud x1_5"></div>
        <div class="cloud x2"></div>
        <div class="cloud x3"></div>
        <div class="cloud x4"></div>
        <div class="cloud x5"></div>
    </div>
    <div class='c'>
        <div class='_404'>500</div>
        <hr>
        <div class='_1'>ERROR</div>
        <div class='_2'>Lỗi thực thi máy chủ</div>
        <a class='btn' href='{% url 'home:homepage' %}'>Quay trở lại trang chủ</a>
    </div>
</body>

</html>

templates/layout.html
% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Enational Library</title>
    <link rel="stylesheet" href="{% static 'home/css/homepage.css' %}">
</head>
<body>
    <h1>Hello world!</h1>
    <img src="{{ magazine.image.url }}" alt="{{ magazine.image.name }}">
    <iframe src="{{ magazine.pdfFile.url }}" width="1000" height="1000" allow="autoplay">
    </iframe>
</object>
</body>
</html>